# name: Cypress Tests
# on:
#   push:
#     branches: [main]
#     pull_request:
# jobs:
#   cypress-run E2E test:
#     runs-on: ubuntu-latest
#     # Runs tests in parallel with matrix strategy https://on.cypress.io/parallelization
#     # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
#     # Also see warning here https://github.com/cypress-io/github-action#parallel
#     strategy:
#       fail-fast: false # https://github.com/cypress-io/github-action/issues/48
#       matrix:
#         containers: [1, 2] # Uses 2 parallel instances
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4 #actions/checkout@v6
#       - name: Cypress run
#         # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
#         uses: cypress-io/github-action@v7
#         with:
#           # Starts web server for E2E tests - replace with your own server invocation
#           # https://docs.cypress.io/app/continuous-integration/overview#Boot-your-server
#           # start: npm start   #comment this becuase my project not run on web server
#           # wait-on: "http://localhost:3000" # Waits for above
#           # Records to Cypress Cloud
#           # https://docs.cypress.io/cloud/get-started/setup
#           install: true
#           command: npm run test1
#           record: true
#           parallel: true # Runs test in parallel using settings above
#         env:
#           # For recording and parallelization you must set your CYPRESS_RECORD_KEY
#           # in GitHub repo → Settings → Secrets → Actions
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           # Create a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Cypress Tests

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [main]
    pull_request:
jobs:
  cypress-run-E2E-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          install: true
          command: npm run test
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.containers }}
          path: cypress/videos
          if-no-files-found: ignore
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.containers }}
          path: cypress/screenshots
          if-no-files-found: ignore
      # - name: Generate Mochawesome Report
      #   run: |
      #     npx mochawesome-merge cypress/reports/**/*.json > mochawesome.json
      #     npx marge mochawesome.json
      # - name: Upload Test Report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-html-report-${{ matrix.containers }}
      #     path: mochawesome-report
      #     if-no-files-found: ignore
      # Upload JSON reports only
      - name: Upload JSON Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: json-reports-${{ matrix.containers }}
          path: cypress/reports
          if-no-files-found: ignore

      - name: Comment PR with test result
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ✅ Cypress Tests Completed
            Check GitHub Actions for details.

      - name: Notify Slack on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "text":"❌ Cypress Tests Failed\nRepository: ${{ github.repository }}\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }' \
          $SLACK_WEBHOOK_URL

merge-report:
  runs-on: ubuntu-latest
  needs: cypress-run-E2E-test

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Install Report Dependencies
      run: |
        npm install mochawesome mochawesome-merge mochawesome-report-generator

    - name: Download Reports
      uses: actions/download-artifact@v4
      with:
        path: reports

    - name: Merge Mochawesome Reports
      run: |
        npx mochawesome-merge reports/**/*.json > mochawesome.json
        npx mochawesome-report-generator mochawesome.json

    - name: Upload Final HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: cypress-html-report
        path: mochawesome-report
